{
  "version": "1.0.0",
  "id": "khaledthesuiman.modButtonLoader",
  "name": "Mod Button Loader",
  "developer": "KhaledTheSuiman",
  "description": "A convenient tool for managing mod buttons without accidental clicks"
}
